import SitePage from "../../components/SitePage";
import credits from "./credits.json";

export const metadata = { title: "Credits | S.V.E.R", description: "The open-source software S.V.E.R uses, with its licenses." };

type Package = { kind: "rust" | "npm" | "other"; name: string; version: string; license: string; url: string; text: string | null };
const { packages, texts } = credits as { packages: Package[]; texts: Record<string, string> };
// Only web links are shown; registry metadata sometimes holds git+ssh or bare paths.
const href = (p: Package) => /^https?:\/\//.test(p.url) ? p.url : p.kind === "rust" ? `https://crates.io/crates/${p.name}` : `https://www.npmjs.com/package/${p.name}`;
const GROUPS: [Package["kind"], string][] = [["other", "Servers and fonts"], ["rust", "Rust crates (the S.V.E.R server)"], ["npm", "npm packages (the website)"]];

/** /credits (docs/CHANNEL_ADDITIONS.md "Credits"): generated by scripts/credits.mjs; CI checks it's current. */
export default function Credits() {
  const users = new Map<string, string[]>();
  for (const p of packages) if (p.text) users.set(p.text, [...(users.get(p.text) ?? []), p.name]);
  return <SitePage path="/credits" title="Credits" intro="S.V.E.R is built on open-source software. These are the packages that ship, with their licenses." wide>
    <p>S.V.E.R itself is open source under the GNU Affero General Public License v3.0. <a href="https://github.com/S-V-E-R/S.V.E.R">Read the source on GitHub</a>.</p>
    <p>Where a package offers a choice of licenses that includes MIT, S.V.E.R uses it under MIT.</p>
    {GROUPS.map(([kind, title]) => {
      const list = packages.filter(p => p.kind === kind);
      return <section key={kind}>
        <h2>{title} <span className="muted">({list.length})</span></h2>
        <div className="table-scroll"><table>
          <thead><tr><th scope="col">Name</th><th scope="col">Version</th><th scope="col">License</th></tr></thead>
          <tbody>{list.map(p => <tr key={`${p.name}@${p.version}`}>
            <td><a href={href(p)} rel="noopener">{p.name}</a></td><td>{p.version}</td>
            <td>{p.text ? <a href={`#license-${p.text}`}>{p.license}</a> : p.license}</td>
          </tr>)}</tbody>
        </table></div>
      </section>;
    })}
    <h2>License texts</h2>
    {Object.entries(texts).map(([id, text]) => <details key={id} id={`license-${id}`}>
      <summary>{(users.get(id) ?? []).slice(0, 6).join(", ")}{(users.get(id)?.length ?? 0) > 6 && ` and ${users.get(id)!.length - 6} more`}</summary>
      <pre className="license-text">{text}</pre>
    </details>)}
  </SitePage>;
}
